In [3]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [4]:
df_full_train = pd.read_csv("/train.csv")
df_test = pd.read_csv("/test.csv")

In [5]:
df_full_train.head()

,id,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,...,Baggage handling,Checkin service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Gender,Customer Type,Type of Travel,Class,satisfaction
0,0,36,694,4,4,4,3,1,4,1,...,4,3,1,0,0.0,Female,Loyal Customer,Personal Travel,Eco,False
1,1,56,651,5,5,5,5,5,4,4,...,5,4,3,0,0.0,Male,Loyal Customer,Business travel,Business,True
2,2,31,1371,3,4,2,5,3,3,3,...,4,5,3,0,0.0,Female,Loyal Customer,Personal Travel,Eco,False
3,3,10,1616,3,5,3,3,3,3,3,...,3,4,3,0,0.0,Male,Loyal Customer,Personal Travel,Eco,False
4,4,23,481,3,4,3,4,5,3,5,...,5,3,5,5,0.0,Female,disloyal Customer,Business travel,Eco,False

In [6]:
df_test.T

,0,1,2,3,4,5,6,7,8,9,...,299834,299835,299836,299837,299838,299839,299840,299841,299842,299843
id,699635,699636,699637,699638,699639,699640,699641,699642,699643,699644,...,999469,999470,999471,999472,999473,999474,999475,999476,999477,999478
Age,25,36,45,45,34,53,15,34,51,56,...,47,30,31,17,41,32,24,33,59,69
Flight Distance,1197,829,472,762,594,2556,1562,1020,3837,946,...,2586,3391,1010,1597,1797,1725,1325,190,678,1044
Inflight wifi service,4,5,4,2,1,4,3,3,0,2,...,1,1,2,2,3,3,3,4,3,2
Departure/Arrival time convenient,4,5,5,2,2,4,5,3,0,3,...,4,1,5,5,3,1,3,5,5,5
Ease of Online booking,4,5,5,2,1,4,3,3,0,1,...,4,1,2,2,3,3,3,4,3,2
Gate location,2,5,5,5,1,4,2,3,4,5,...,4,1,1,2,3,3,4,3,2,2
Food and drink,3,5,4,3,2,2,2,2,3,1,...,1,3,3,1,3,3,3,3,4,4
Online boarding,4,4,4,2,1,4,3,5,4,4,...,1,3,2,2,5,3,3,4,3,2
Seat comfort,3,5,4,3,2,5,2,4,5,4,...,1,3,3,1,4,3,3,3,5,4
Inflight entertainment,3,5,4,3,2,5,2,4,3,1,...,1,3,3,1,3,3,2,3,5,4
On-board service,2,1,3,3,2,5,4,4,3,1,...,3,5,3,4,3,3,1,4,4,5
Leg room service,5,2,3,4,4,5,3,4,4,1,...,3,4,3,5,3,3,2,3,4,1
Baggage handling,2,4,1,4,2,5,3,4,3,1,...,4,5,3,4,3,3,3,2,4,3
Checkin service,1,3,3,4,1,3,3,5,4,4,...,1,3,2,4,4,1,5,2,4,1
Cleanliness,3,5,4,3,2,3,2,3,3,4,...,1,3,3,1,4,3,3,3,5,4
Departure Delay in Minutes,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,15,0,0,0,4,0
Arrival Delay in Minutes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0,0.0
Gender,Female,Male,Male,Female,Male,Male,Male,Female,Male,Female,...,Male,Female,Male,Male,Male,Female,Female,Male,Male,Male
Customer Type,disloyal Customer,Loyal Customer,Loyal Customer,disloyal Customer,Loyal Customer,Loyal Customer,Loyal Customer,Loyal Customer,Loyal Customer,Loyal Customer,...,Loyal Customer,Loyal Customer,Loyal Customer,Loyal Customer,Loyal Customer,Loyal Customer,disloyal Customer,Loyal Customer,Loyal Customer,Loyal Customer
Type of Travel,Business travel,Business travel,Business travel,Business travel,Personal Travel,Business travel,Personal Travel,Business travel,Business travel,Personal Travel,...,Business travel,Business travel,Personal Travel,Personal Travel,Business travel,Business travel,Business travel,Personal Travel,Personal Travel,Personal Travel
Class,Eco,Eco,Eco,Business,Eco Plus,Business,Eco,Business,Business,Eco,...,Business,Business,Eco,Eco,Business,Business,Eco,Eco,Eco,Eco

In [7]:
df_full_train.T

,0,1,2,3,4,5,6,7,8,9,...,699625,699626,699627,699628,699629,699630,699631,699632,699633,699634
id,0,1,2,3,4,5,6,7,8,9,...,699625,699626,699627,699628,699629,699630,699631,699632,699633,699634
Age,36,56,31,10,23,34,36,57,60,44,...,47,49,49,25,29,57,30,49,61,42
Flight Distance,694,651,1371,1616,481,584,1763,861,581,588,...,308,552,1464,759,967,612,862,3148,679,813
Inflight wifi service,4,5,3,3,3,4,5,1,3,3,...,2,2,3,2,1,2,2,5,5,1
Departure/Arrival time convenient,4,5,4,5,4,4,5,3,3,3,...,5,5,4,5,5,1,2,5,2,1
Ease of Online booking,4,5,2,3,3,4,5,1,3,2,...,2,3,3,3,1,1,2,5,2,0
Gate location,3,5,5,3,4,4,5,3,3,2,...,3,5,1,3,3,1,3,5,2,4
Food and drink,1,5,3,3,5,1,3,4,5,2,...,5,3,2,5,2,1,4,4,5,3
Online boarding,4,4,3,3,3,4,4,4,4,3,...,5,3,4,3,1,3,2,4,4,0
Seat comfort,1,4,3,3,5,1,4,4,5,2,...,5,3,4,5,2,3,4,4,4,3
Inflight entertainment,1,5,3,3,5,1,3,5,4,2,...,2,3,4,5,2,2,4,5,5,3
On-board service,3,5,4,4,5,3,4,5,4,5,...,3,3,4,3,4,2,2,5,4,4
Leg room service,4,5,3,5,4,3,4,0,4,4,...,2,3,3,2,4,2,5,5,5,4
Baggage handling,4,5,4,3,5,4,4,5,4,4,...,3,5,4,4,5,2,4,5,5,3
Checkin service,3,4,5,4,3,4,3,4,4,1,...,5,4,4,3,4,2,2,5,5,4
Cleanliness,1,3,3,3,5,1,3,2,5,2,...,5,3,4,5,2,4,4,5,1,3
Departure Delay in Minutes,0,0,0,0,5,0,0,0,0,0,...,0,0,0,0,0,0,24,0,0,0
Arrival Delay in Minutes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,34.0,0.0,0.0,0.0
Gender,Female,Male,Female,Male,Female,Female,Female,Female,Female,Female,...,Female,Male,Female,Female,Male,Female,Female,Male,Female,Male
Customer Type,Loyal Customer,Loyal Customer,Loyal Customer,Loyal Customer,disloyal Customer,disloyal Customer,Loyal Customer,Loyal Customer,Loyal Customer,disloyal Customer,...,Loyal Customer,Loyal Customer,Loyal Customer,disloyal Customer,Loyal Customer,Loyal Customer,disloyal Customer,Loyal Customer,Loyal Customer,Loyal Customer
Type of Travel,Personal Travel,Business travel,Personal Travel,Personal Travel,Business travel,Business travel,Business travel,Personal Travel,Business travel,Business travel,...,Personal Travel,Personal Travel,Personal Travel,Business travel,Personal Travel,Business travel,Business travel,Business travel,Business travel,Personal Travel
Class,Eco,Business,Eco,Eco,Eco,Business,Business,Eco,Business,Eco,...,Eco,Eco,Eco,Business,Eco,Eco,Eco,Business,Eco,Eco
satisfaction,False,True,False,False,False,False,True,False,True,False,...,False,False,False,False,False,False,False,True,True,False

In [8]:
df_full_train.dtypes

id                                     int64
Age                                    int64
Flight Distance                        int64
Inflight wifi service                  int64
Departure/Arrival time convenient      int64
Ease of Online booking                 int64
Gate location                          int64
Food and drink                         int64
Online boarding                        int64
Seat comfort                           int64
Inflight entertainment                 int64
On-board service                       int64
Leg room service                       int64
Baggage handling                       int64
Checkin service                        int64
Cleanliness                            int64
Departure Delay in Minutes             int64
Arrival Delay in Minutes             float64
Gender                                object
Customer Type                         object
Type of Travel                        object
Class                                 object
satisfaction                            bool
dtype: object

In [9]:
df_full_train.columns = df_full_train.columns.str.lower().str.replace(' ', '_')
df_full_train.columns = df_full_train.columns.str.lower().str.replace('/', '_')

categorical_columns = list(df_full_train.dtypes[df_full_train.dtypes == 'str'].index)

for c in categorical_columns:
    df_full_train[c] = df_full_train[c].str.lower().str.replace(' ', '_')

In [10]:
df_test.columns = df_test.columns.str.lower().str.replace(' ', '_')
df_test.columns = df_test.columns.str.lower().str.replace('/', '_')

categorical_columns = list(df_test.dtypes[df_test.dtypes == 'str'].index)

for c in categorical_columns:
    df_test[c] = df_test[c].str.lower().str.replace(' ', '_')

In [11]:
df_full_train.customer_type.value_counts()

customer_type
Loyal Customer       576990
disloyal Customer    122645
Name: count, dtype: int64

In [12]:
df_full_train.type_of_travel.value_counts()

type_of_travel
Business travel    497441
Personal Travel    202194
Name: count, dtype: int64

In [13]:
df_full_train["satisfaction"].value_counts()

satisfaction
False    389296
True     310339
Name: count, dtype: int64

In [14]:
df_full_train["class"].value_counts()

class
Business    342212
Eco         327404
Eco Plus     30019
Name: count, dtype: int64

In [15]:
df_full_train.isnull().sum()

id                                     0
age                                    0
flight_distance                        0
inflight_wifi_service                  0
departure_arrival_time_convenient      0
ease_of_online_booking                 0
gate_location                          0
food_and_drink                         0
online_boarding                        0
seat_comfort                           0
inflight_entertainment                 0
on-board_service                       0
leg_room_service                       0
baggage_handling                       0
checkin_service                        0
cleanliness                            0
departure_delay_in_minutes             0
arrival_delay_in_minutes             292
gender                                 0
customer_type                          0
type_of_travel                         0
class                                  0
satisfaction                           0
dtype: int64

In [16]:
df_full_train.arrival_delay_in_minutes = df_full_train.arrival_delay_in_minutes.fillna(df_full_train.arrival_delay_in_minutes.median())

In [17]:
df_test.isnull().sum()

id                                     0
age                                    0
flight_distance                        0
inflight_wifi_service                  0
departure_arrival_time_convenient      0
ease_of_online_booking                 0
gate_location                          0
food_and_drink                         0
online_boarding                        0
seat_comfort                           0
inflight_entertainment                 0
on-board_service                       0
leg_room_service                       0
baggage_handling                       0
checkin_service                        0
cleanliness                            0
departure_delay_in_minutes             0
arrival_delay_in_minutes             130
gender                                 0
customer_type                          0
type_of_travel                         0
class                                  0
dtype: int64

In [18]:
df_test.arrival_delay_in_minutes = df_test.arrival_delay_in_minutes.fillna(df_test.arrival_delay_in_minutes.median())

In [19]:
df_full_train.satisfaction = df_full_train.satisfaction.astype(int)

In [20]:
df_full_train.satisfaction.value_counts(normalize = True)

satisfaction
0    0.556427
1    0.443573
Name: proportion, dtype: float64

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
df_train, df_val = train_test_split(df_full_train, test_size = 0.2, random_state = 42)

In [23]:
len(df_train), len(df_val)

(559708, 139927)

In [24]:
y_train = df_train.satisfaction.values
y_val = df_val.satisfaction.values
y_full_train = df_full_train.satisfaction.values

In [25]:
df_full_train = df_full_train.reset_index(drop = True)
df_train = df_train.reset_index(drop = True)
df_test = df_test.reset_index(drop = True)

In [26]:
del df_full_train['satisfaction']
del df_train['satisfaction']
del df_val['satisfaction']

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction import DictVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import roc_auc_score

In [28]:
train_dicts = df_train.to_dict(orient = "records")

In [29]:
dv = DictVectorizer(sparse = False)
X_train = dv.fit_transform(train_dicts)

In [30]:
lr = make_pipeline(
    StandardScaler(),
    LogisticRegression(
        solver='lbfgs',
        C=1.0,
        max_iter=300,
        random_state=42
    )
)
lr.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression',
                 LogisticRegression(max_iter=300, random_state=42))])

In [31]:
val_dicts = df_val.to_dict(orient = "records")
X_val = dv.transform(val_dicts)

In [32]:
y_pred = lr.predict_proba(X_val)[:,1]

In [38]:
print(roc_auc_score(y_val, y_pred))

0.9213927383244249

In [39]:
from sklearn.tree import DecisionTreeClassifier

In [40]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [44]:
y_pred = dt.predict_proba(X_val)[:, 1]
print(roc_auc_score(y_val, y_pred))

0.8647211052047767

In [46]:
y_pred = dt.predict_proba(X_train)[:, 1]
print(roc_auc_score(y_train, y_pred))

1.0

In [47]:
depths = [1, 2, 3, 4, 5, 6, 10, 15, 20, None]

for depth in depths:
    dt = DecisionTreeClassifier(max_depth=depth)
    dt.fit(X_train, y_train)

    y_pred = dt.predict_proba(X_val)[:, 1]
    auc = roc_auc_score(y_val, y_pred)

    print('%4s -> %.3f' % (depth, auc))

   1 -> 0.813
   2 -> 0.875
   3 -> 0.909
   4 -> 0.928
   5 -> 0.938
   6 -> 0.945
  10 -> 0.951
  15 -> 0.940
  20 -> 0.911
None -> 0.864

In [49]:
dt = DecisionTreeClassifier(max_depth=10, min_samples_leaf=100)
dt.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=10, min_samples_leaf=100)

In [72]:
y_pred = dt.predict_proba(X_val)[:, 1]
auc = roc_auc_score(y_val, y_pred)
print(auc)

0.9540060779399127

In [55]:
dicts_full_train = df_full_train.to_dict(orient='records')

dv = DictVectorizer(sparse=False)
X_full_train = dv.fit_transform(dicts_full_train)
dt.fit(X_full_train, y_full_train)

dicts_test = df_test.to_dict(orient='records')
X_test = dv.transform(dicts_test)

In [56]:
predictions = dt.predict(X_test)

In [57]:
submission = pd.DataFrame({
     'id': df_test['id'],
     'satisfaction': predictions
 })

submission.to_csv('submission.csv', index=False)