In [78]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [79]:
df_train= pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [80]:
df_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [81]:
df_test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [82]:
df_train.shape

(891, 12)

In [83]:
df_test.shape

(418, 11)

In [84]:
df_train.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [85]:
df_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [86]:
df_train['Ticket'].value_counts()

Ticket
347082             7
1601               7
CA. 2343           7
3101295            6
CA 2144            6
                  ..
SOTON/OQ 392076    1
211536             1
112053             1
111369             1
370376             1
Name: count, Length: 681, dtype: int64

In [87]:
df_train['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [88]:
df_train['SibSp'].value_counts()

SibSp
0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: count, dtype: int64

In [89]:
df_train['SibSp'].value_counts()

SibSp
0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: count, dtype: int64

In [90]:
df_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [91]:
df_test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [92]:
df_train.columns = df_train.columns.str.lower().str.replace(' ', '_')

categorical_train_columns = list(df_train.dtypes[df_train.dtypes == 'str'].index)

for c in categorical_train_columns:
    df_train[c] = df_train[c].str.lower().str.replace(' ', '_')

df_test.columns = df_test.columns.str.lower().str.replace(' ', '_')

categorical_test_columns = list(df_test.dtypes[df_test.dtypes == 'str'].index)

for c in categorical_test_columns:
    df_test[c] = df_test[c].str.lower().str.replace(' ', '_')

In [93]:
df_train.age = df_train.age.fillna(df_train.age.median())
df_train.embarked = df_train.embarked.fillna(df_train.embarked.mode()[0])
df_test.age = df_test.age.fillna(df_test.age.median())
df_test.fare = df_test.fare.fillna(0)

In [94]:
df_train.columns

Index(['passengerid', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='str')

In [95]:
df_test.columns

Index(['passengerid', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch',
       'ticket', 'fare', 'cabin', 'embarked'],
      dtype='str')

In [96]:
test_passenger_ids = df_test.passengerid

In [97]:
numeric = ['pclass', 'age', 'sibsp', 'parch', 'fare']
cat = ['sex', 'embarked']

In [129]:
X = df_train[numeric + cat]
y = df_train.survived
X_test = df_test[numeric + cat]

In [130]:
from sklearn.model_selection import train_test_split

In [131]:
X_train , X_val, y_train, y_val = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [132]:
len(X_train), len(X_val)

(712, 179)

In [133]:
X_train = X_train.reset_index(drop = True)
X_val = X_val.reset_index(drop = True)

In [134]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

In [135]:
X_train_num = X_train[numeric].values
scaler = StandardScaler()

X_train_num = scaler.fit_transform(X_train_num)

In [136]:
ohe = OneHotEncoder(sparse_output = False, handle_unknown = 'ignore')

In [137]:
X_train_cat = ohe.fit_transform(X_train[cat].values)

In [138]:
print(ohe.get_feature_names_out())

['x0_female' 'x0_male' 'x1_c' 'x1_q' 'x1_s']

In [139]:
X_train = np.column_stack([X_train_num, X_train_cat])

In [140]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [141]:
model = LogisticRegression(solver='lbfgs', C=1.0, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [142]:
model.predict_proba(X_train)

array([[0.67175974, 0.32824026],
       [0.73496267, 0.26503733],
       [0.90528766, 0.09471234],
       ...,
       [0.95717567, 0.04282433],
       [0.06980852, 0.93019148],
       [0.49205571, 0.50794429]], shape=(712, 2))

In [143]:
X_val_num = X_val[numeric].values
X_val_num = scaler.transform(X_val_num)

X_val_cat = ohe.transform(X_val[cat].values)

X_val = np.column_stack([X_val_num, X_val_cat])

In [144]:
y_pred = model.predict_proba(X_val)[:, 1]
accuracy_score(y_val, y_pred >= 0.5)

0.8100558659217877

In [145]:
X_full_train_num = X[numeric].values
scaler = StandardScaler()

X_full_train_num = scaler.fit_transform(X_full_train_num)

In [146]:
X_full_train_cat = ohe.fit_transform(X[cat].values)

In [147]:
print(ohe.get_feature_names_out())

['x0_female' 'x0_male' 'x1_c' 'x1_q' 'x1_s']

In [148]:
X_full_train = X_train = np.column_stack([X_full_train_num, X_full_train_cat])

In [152]:
y_full_train = y.values

In [154]:
model = LogisticRegression(solver='lbfgs', C=1.0, random_state=42) 
model.fit(X_full_train, y_full_train)

LogisticRegression(random_state=42)

In [160]:
predictions = model.predict(X_test)

In [161]:
submission = pd.DataFrame({
    'PassengerId': df_test['passengerid'],
    'Survived': predictions
})

submission.to_csv('submission.csv', index=False)